version: '3'

services:
  hedge-fund-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hedge-fund-app
    restart: always
    environment:
      - NODE_ENV=development
      - ENZYME_API_TOKEN=${ENZYME_API_TOKEN}
      - ENZYME_VAULT_ADDRESS=${ENZYME_VAULT_ADDRESS}
    volumes:
      - ./public:/app/public
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/senyka.org/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/senyka.org/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      - hedge-fund-app
    networks:
      - web

networks:
  web:
    external: true 